secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>

default: &default
  qiwa_domain: "qiwa.info"
  root_domain: 'localhost'
  redis: &default_redis
    host: <%= ENV['DEVELOPMENT_QUIRE_BACKEND_REDIS_HOST'] %>
    port:  <%= ENV['DEVELOPMENT_QUIRE_BACKEND_REDIS_PORT'] %>
    namespace: <%= ENV['DEVELOPMENT_REDIS_NAMESPACE'] %>
    notification:
      db: <%= ENV['DEVELOPMENT_NOTIFICATION_REDIS_DB'] %>
    system_configuration_redis_cache:
      db: <%= ENV['DEVELOPMENT_CONFIGURATIONS_CACHE_REDIS_DB'] %>
    Auth_token_blacklist:
      db: <%= ENV['DEVELOPMENT_AUTH_TOKENS_BLACKLIST_DB'] %>
    features_flags:
      db: <%= ENV['DEVELOPMENT_FEATURES_FLAGS_DB'] %>
    rescue:
      db: <%= ENV['DEVELOPMENT_QUIRE_BACKEND_REDIS_DB'] %>
  quire_client_id: <%= ENV['QUIRE_CLIENT_ID'] %>
  quire_client_secret: <%= ENV['QUIRE_CLIENT_SECRET'] %>
  quire_base_url: <%= ENV['QUIRE_API_BASE_URL'] %>
  frontend_url: <%= ENV['FRONTEND_URL'] %>

development:
  <<: *default
  frontend_url:  <%= ENV['FRONTEND_DEVELOPMENT_URL'] %>

test:
  <<: *default
  redis:
    <<: *default_redis
    namespace: <%= ENV['TEST_REDIS_NAMESPACE'] %>
    system_configuration_redis_cache:
      db: <%= ENV['TEST_CONFIGURATIONS_CACHE_REDIS_DB'] %>
    rescue:
      db: <%= ENV['TEST_QUIRE_BACKEND_REDIS_DB'] %>
    features_flags:
      db: <%= ENV['TEST_FEATURES_FLAGS_DB'] %>
  frontend_url:  <%= ENV['FRONTEND_TEST_URL'] %>


staging:
  <<: *default
  frontend_url:  <%= ENV['FRONTEND_STAGING_URL'] %>
  root_domain: <%= ENV['STAGING_COOKIES_DOMAIN'] %>
  redis:
    host: <%= ENV['STAGING_QUIRE_BACKEND_REDIS_HOST'] %>
    port:  <%= ENV['STAGING_QUIRE_BACKEND_REDIS_PORT'] %>
    namespace: <%= ENV['STAGING_REDIS_NAMESPACE'] %>
    notification:
      db: <%= ENV['STAGING_NOTIFICATION_REDIS_DB'] %>
    system_configuration_redis_cache:
      db: <%= ENV['STAGING_CONFIGURATIONS_CACHE_REDIS_DB'] %>
    features_flags:
      db: <%= ENV['STAGING_FEATURES_FLAGS_DB'] %>
    Auth_token_blacklist:
      db: <%= ENV['STAGING_AUTH_TOKENS_BLACKLIST_DB'] %>
    rescue:
      db: <%= ENV['STAGING_QUIRE_BACKEND_REDIS_DB'] %>

production:
  <<: *default
  frontend_url:  <%= ENV['FRONTEND_PRODUCTION_URL'] %>
  root_domain: <%= ENV['PRODUCTION_COOKIES_DOMAIN'] %>
  websocket_frontend_url:  <%= ENV['PRODUCITON_WEBSOCKET_FRONTEND_URL'] %>
  redis:
    host: <%= ENV['PRODUCTION_QUIRE_BACKEND_REDIS_HOST'] %>
    master_name: <%= ENV['PRODUCTION_QUIRE_BACKEND_REDIS_MASTER_NAME'] %>
    namespace: <%= ENV['PRODUCTION_REDIS_NAMESPACE'] %>
    notification:
      db: <%= ENV['PRODUCTION_NOTIFICATION_REDIS_DB'] %>
    system_configuration_redis_cache:
      db: <%= ENV['PRODUCTION_CONFIGURATIONS_CACHE_REDIS_DB'] %>
    Auth_token_blacklist:
      db: <%= ENV['PRODUCTION_AUTH_TOKENS_BLACKLIST_DB'] %>
    rescue:
      db: <%= ENV['PRODUCTION_QUIRE_BACKEND_REDIS_DB'] %>
    features_flags:
      db: <%= ENV['PRODUCTION_FEATURES_FLAGS_DB'] %>
    sentinels:
      - {host: mrn-redis1, port: 26379}
      - {host: mrn-redis2, port: 26379}
      - {host: mrn-redis3, port: 26379}
