development:
  adapter: redis
  url: <%= "redis://#{ENV["DEVELOPMENT_QUIRE_BACKEND_REDIS_HOST"]}:#{ENV["DEVELOPMENT_QUIRE_BACKEND_REDIS_PORT"]}/#{ENV["DEVELOPMENT_NOTIFICATION_REDIS_DB"]}" %>

test:
  adapter: test

staging:
  adapter: redis
  url: <%= "redis://#{ENV["STAGING_QUIRE_BACKEND_REDIS_HOST"]}:#{ENV["STAGING_QUIRE_BACKEND_REDIS_PORT"]}/#{ENV["STAGING_NOTIFICATION_REDIS_DB"]}" %>

production:
  adapter: redis
  channel_prefix: quire_backend_production
  host: <%= ENV['PRODUCTION_QUIRE_BACKEND_REDIS_HOST'] %>
  db: <%= ENV['PRODUCTION_NOTIFICATION_REDIS_DB'] %>
  sentinels:
    - {host: mrn-redis1, port: 26379}
    - {host: mrn-redis2, port: 26379}
    - {host: mrn-redis3, port: 26379}
